pipeline {
    agent {
        node {
            label 'et-qe-slave-other'
        }
    }
    stages('Run E2E Testing') {
        stage('Prepare E2E ET Server') {
            steps {
                build(job:"Prepare_ET_Server_For_Build_Testing", parameters: [[$class: 'StringParameterValue', name: 'ET_Testing_Server', value: "${ET_Testing_Server}"], [$class: 'StringParameterValue', name: 'et_build_name_or_id', value: "${et_build_name_or_id}"]])
            }
        }
        stage('Initialize Pub and Pulp Servers') {
            steps {
                build(job:"Initialize_Testing_Sever_Pub_Pulp", parameters: [[$class: 'StringParameterValue', name: 'username', value: "${username}"], [$class: 'hudson.model.PasswordParameterValue', name: 'password', value: "${password}"],[$class: 'StringParameterValue', name: 'pub_server', value:"${pub_server}"], [$class: 'StringParameterValue', name: 'pulp_rpm_server', value: "${pulp_rpm_server}"], [$class: 'StringParameterValue', name: 'pulp_docker_server', value: "${pulp_docker_server}"]])
            }
        }
        stage('Upgrade Pub and Pulp Servers') {
            when {
                expression { "${CD_RC}" == 'true' }
            }
            steps {
                build(job:"Parser_Performance_Result", parameters: [[$class: 'StringParameterValue', name: 'pub_jenkins_build', value: "${pub_jenkins_build}"], [$class: 'StringParameterValue', name: 'pulp_build_for_rpm', value: "${pulp_build_for_rpm}"], [$class: 'StringParameterValue', name: 'pulp_rpm_build', value: "${pulp_rpm_build}" ], [$class: 'StringParameterValue', name: 'pulp_cdn_distributor_build', value: "${pulp_cdn_distributor_build}"], [$class: 'StringParameterValue', name: 'pulp_build_for_docker', value: "${pulp_build_for_docker}"], [$class: 'StringParameterValue', name: 'pulp_docker_build', value: "${pulp_docker_build}"]])
            }
        }
        stage('Run E2E Testing and Show report') {
            steps {
                build(job:"Trigger_E2E_Testing", parameters: [[$class: 'StringParameterValue', name: 'username', value: "${username}"], [$class: 'hudson.model.PasswordParameterValue', name: 'password', value: "${password}"],[$class: 'StringParameterValue', name: 'e2e_jenkins_build_name', value:"${e2e_jenkins_build_name}"], [$class: 'StringParameterValue', name: 'e2e_expect_run_time', value: "${e2e_expect_run_time}"], [$class: 'StringParameterValue', name: 'et_build_name_or_id', value: "${et_build_name_or_id}"]])
            }
        }
    }
}
